Add foreign configuration support
Naudit/pystorcli2 pull request #11
Opened 2023-04-20 17:09 UTC by dgilbert101

The following pull request adds methods to deal with foreign configurations:
- has_foreign_configurations
- import_foreign_configurations
- delete_foreign_configurations

2023-04-21 08:23 UTC, ralequi commented on pystorcli2/foreignconfig/__init__.py
> +class ForeignConfigurations(object):
Hi,
Sure, totally agree with @ulmitov .
I don't clearly see the benefit of an independent object when it only provides 3 useful methods (has, import & delete FC)

2023-04-21 12:56 UTC, dgilbert101 commented on pystorcli2/foreignconfig/__init__.py
> +class ForeignConfigurations(object):
ok, i can refactor. when I originally started, I expected the /fx functionality to work. Only to find out it is just /fall.

2023-04-24 15:17 UTC, dgilbert101 commented on pystorcli2/foreignconfig/__init__.py
> +class ForeignConfigurations(object):
The docs are incorrect. If you look at the output from the latest versions of storcli or perccli, you can only use /fall

    $ /opt/MegaRAID/perccli/perccli64 /fall help
    PercCli SAS Customization Utility Ver 007.1623.0000.0000 May 17, 2021
    (c)Copyright 2021, Broadcom Inc. All Rights Reserved.

    perccli /cx/fall show [all] [securityKey = xxx]
    perccli /cx/fall del|delete [securityKey = xxx]
    perccli /cx/fall import [preview] [securityKey = xxx]

    $ /opt/MegaRAID/storcli/storcli64 /fall help
    StorCli SAS Customization Utility Ver 007.2408.0000.0000 Nov 15, 2022
    (c)Copyright 2022, Broadcom Inc. All Rights Reserved.

    storcli /cx/fall show [all] [securityKey = xxx]
    storcli /cx/fall del|delete [securityKey = xxx]
    storcli /cx/fall import [preview] [securityKey = xxxx

2023-04-24 15:42 UTC, ralequi commented on pystorcli2/controller/__init__.py
> +            'del'
maybe you want to say `import` ?

2023-04-26 13:40 UTC, dgilbert101 commented on pystorcli2/controller/__init__.py
> +            'del'
hah, yeah, definitely should

2023-04-26 13:53 UTC, dgilbert101 commented on pystorcli2/controller/__init__.py
> +            'show'
I've added it, but I currently have no way to test this.

2023-04-27 10:40 UTC, ralequi approved these changes

2023-04-27 16:03 UTC, ralequi requested changes
It seems that some /fall access causes raising exceptions.

We would have to handle those things. Check issue #13

2023-05-05 08:28 UTC, ralequi approved these changes
I think everything is OK now. @ulmitov something to add?

2023-05-05 09:35 UTC, ralequi commented
Thx, Let me check

2023-05-08 08:48 UTC, ralequi commented
Ok, I'm going to merge this and finish it on develop branch

Thanks @dgilbert101 & @ulmitov

2023-05-08 08:48 UTC, merged